### ISSUE TITLE
0.0.2 release?

### ISSUE THREAD

**Issue by doy** [antifuchs/godwrap#1]
i'm packaging this up for arch linux (https://aur.archlinux.org/packages/godwrap/) and it looks like there are a bunch of useful bugfixes on master that haven't made it to a release yet (in particular, i'd love to be able to stop having to manually restart telegraf whenever a new type of cron job runs). would it be reasonable to just tag the current master?

**Comment by antifuchs** [comment]
Aah, thanks for the reminder! I pushed [`v0.0.2`](https://github.com/antifuchs/godwrap/compare/v0.0.1...v0.0.2) just now - thanks for packaging it up!
